# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-27 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import store_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('store_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to=store_data.models.product_images_directory_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store_data.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
