# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-28 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import store_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('store_data', '0002_auto_20190727_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('item_code', models.CharField(blank=True, max_length=30, null=True)),
                ('price_range', models.CharField(blank=True, help_text='range of price for this product', max_length=50, null=True)),
                ('availability', models.CharField(blank=True, help_text='availability of this product', max_length=50, null=True)),
                ('style', models.CharField(blank=True, help_text='style of this product', max_length=50, null=True)),
                ('color', models.CharField(blank=True, help_text='color of this product', max_length=50, null=True)),
                ('panel_thickness_imperial', models.CharField(blank=True, help_text='panel thickness of this product', max_length=50, null=True)),
                ('panel_thickness_metric', models.CharField(blank=True, help_text='panel thickness of this product', max_length=50, null=True)),
                ('series', models.CharField(blank=True, help_text='series of this product', max_length=50, null=True)),
                ('maximum_operating_temperature_imperial', models.CharField(blank=True, max_length=50, null=True)),
                ('maximum_operating_temperature_metric', models.CharField(blank=True, max_length=50, null=True)),
                ('minimum_operating_temperature_imperial', models.CharField(blank=True, max_length=50, null=True)),
                ('minimum_operating_temperature_metric', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_temperature_range_imperial', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_temperature_range_metric', models.CharField(blank=True, max_length=50, null=True)),
                ('overall_width_metric', models.CharField(blank=True, max_length=50, null=True)),
                ('overall_width_imperial', models.CharField(blank=True, max_length=50, null=True)),
                ('full_material', models.CharField(blank=True, max_length=50, null=True)),
                ('material_flammability_standard', models.CharField(blank=True, max_length=50, null=True)),
                ('package_quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(help_text='product name of this variant', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store_data.Product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='VariantImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to=store_data.models.variant_images_directory_path)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store_data.Variant')),
            ],
        ),
        migrations.RemoveField(
            model_name='variants',
            name='product',
        ),
        migrations.AddField(
            model_name='producttype',
            name='competitor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='store_data.Competitor'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
