# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-28 17:30
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_data', '0003_auto_20190728_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, max_length=30, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, max_length=30, populate_from='title', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competitor',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=30, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=30, populate_from='name', unique=True),
        ),
    ]
