# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-28 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_data', '0004_auto_20190728_1730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
        migrations.RenameModel(
            old_name='VariantImages',
            new_name='VariantImage',
        ),
    ]
