# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_data', '0005_auto_20190728_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(blank=True, help_text='stock status of this product', max_length=20, null=True, verbose_name='stock status'),
        ),
    ]
