# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-31 17:35
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store_data', '0006_auto_20190729_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='price_range',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='full_material',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='material_flammability_standard',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='maximum_operating_temperature_imperial',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='maximum_operating_temperature_metric',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='minimum_operating_temperature_imperial',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='minimum_operating_temperature_metric',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='operating_temperature_range_imperial',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='operating_temperature_range_metric',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='overall_width_imperial',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='overall_width_metric',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='package_quantity',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='panel_thickness_imperial',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='panel_thickness_metric',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='series',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='style',
        ),
        migrations.AddField(
            model_name='variant',
            name='specification',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
    ]
