# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-31 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_data', '0007_auto_20190731_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='unit_price',
            field=models.CharField(blank=True, help_text='price per unit product', max_length=30, null=True),
        ),
    ]
