# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-02 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_data', '0012_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='competitor',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_types'),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.ImageField(upload_to='variants'),
        ),
    ]
